//go:build !ignore_autogenerated

/*
Copyright 2024 Nokia.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	infrav1alpha1 "github.com/kuidio/kuid/apis/backend/infra/v1alpha1"
	ipamv1alpha1 "github.com/kuidio/kuid/apis/backend/ipam/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Device) DeepCopyInto(out *Device) {
	*out = *in
	if in.nd != nil {
		in, out := &in.nd, &out.nd
		*out = new(NetworkDevice)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Device.
func (in *Device) DeepCopy() *Device {
	if in == nil {
		return nil
	}
	out := new(Device)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Network) DeepCopyInto(out *Network) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Network.
func (in *Network) DeepCopy() *Network {
	if in == nil {
		return nil
	}
	out := new(Network)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Network) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkBridge) DeepCopyInto(out *NetworkBridge) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]*NetworkInterface, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkInterface)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkBridge.
func (in *NetworkBridge) DeepCopy() *NetworkBridge {
	if in == nil {
		return nil
	}
	out := new(NetworkBridge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigProtocolsBGP) DeepCopyInto(out *NetworkConfigProtocolsBGP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigProtocolsBGP.
func (in *NetworkConfigProtocolsBGP) DeepCopy() *NetworkConfigProtocolsBGP {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigProtocolsBGP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesign) DeepCopyInto(out *NetworkDesign) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesign.
func (in *NetworkDesign) DeepCopy() *NetworkDesign {
	if in == nil {
		return nil
	}
	out := new(NetworkDesign)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkDesign) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulation) DeepCopyInto(out *NetworkDesignEncapsulation) {
	*out = *in
	if in.VXLAN != nil {
		in, out := &in.VXLAN, &out.VXLAN
		*out = new(NetworkDesignEncapsulationVXLAN)
		**out = **in
	}
	if in.MPLS != nil {
		in, out := &in.MPLS, &out.MPLS
		*out = new(NetworkDesignEncapsulationMPLS)
		(*in).DeepCopyInto(*out)
	}
	if in.SRV6 != nil {
		in, out := &in.SRV6, &out.SRV6
		*out = new(NetworkDesignEncapsulationSRv6)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulation.
func (in *NetworkDesignEncapsulation) DeepCopy() *NetworkDesignEncapsulation {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulationMPLS) DeepCopyInto(out *NetworkDesignEncapsulationMPLS) {
	*out = *in
	if in.LDP != nil {
		in, out := &in.LDP, &out.LDP
		*out = new(NetworkDesignEncapsulationMPLSLDP)
		**out = **in
	}
	if in.SR != nil {
		in, out := &in.SR, &out.SR
		*out = new(NetworkDesignEncapsulationMPLSSR)
		**out = **in
	}
	if in.RSVP != nil {
		in, out := &in.RSVP, &out.RSVP
		*out = new(NetworkDesignEncapsulationMPLSRSVP)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulationMPLS.
func (in *NetworkDesignEncapsulationMPLS) DeepCopy() *NetworkDesignEncapsulationMPLS {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulationMPLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulationMPLSLDP) DeepCopyInto(out *NetworkDesignEncapsulationMPLSLDP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulationMPLSLDP.
func (in *NetworkDesignEncapsulationMPLSLDP) DeepCopy() *NetworkDesignEncapsulationMPLSLDP {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulationMPLSLDP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulationMPLSRSVP) DeepCopyInto(out *NetworkDesignEncapsulationMPLSRSVP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulationMPLSRSVP.
func (in *NetworkDesignEncapsulationMPLSRSVP) DeepCopy() *NetworkDesignEncapsulationMPLSRSVP {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulationMPLSRSVP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulationMPLSSR) DeepCopyInto(out *NetworkDesignEncapsulationMPLSSR) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulationMPLSSR.
func (in *NetworkDesignEncapsulationMPLSSR) DeepCopy() *NetworkDesignEncapsulationMPLSSR {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulationMPLSSR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulationMPLSSRv6MicroSID) DeepCopyInto(out *NetworkDesignEncapsulationMPLSSRv6MicroSID) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulationMPLSSRv6MicroSID.
func (in *NetworkDesignEncapsulationMPLSSRv6MicroSID) DeepCopy() *NetworkDesignEncapsulationMPLSSRv6MicroSID {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulationMPLSSRv6MicroSID)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulationSRv6) DeepCopyInto(out *NetworkDesignEncapsulationSRv6) {
	*out = *in
	if in.MicroSID != nil {
		in, out := &in.MicroSID, &out.MicroSID
		*out = new(NetworkDesignEncapsulationMPLSSRv6MicroSID)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulationSRv6.
func (in *NetworkDesignEncapsulationSRv6) DeepCopy() *NetworkDesignEncapsulationSRv6 {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulationSRv6)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignEncapsulationVXLAN) DeepCopyInto(out *NetworkDesignEncapsulationVXLAN) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignEncapsulationVXLAN.
func (in *NetworkDesignEncapsulationVXLAN) DeepCopy() *NetworkDesignEncapsulationVXLAN {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignEncapsulationVXLAN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignInterfaceParameters) DeepCopyInto(out *NetworkDesignInterfaceParameters) {
	*out = *in
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]ipamv1alpha1.Prefix, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignInterfaceParameters.
func (in *NetworkDesignInterfaceParameters) DeepCopy() *NetworkDesignInterfaceParameters {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignInterfaceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignInterfaces) DeepCopyInto(out *NetworkDesignInterfaces) {
	*out = *in
	if in.Loopback != nil {
		in, out := &in.Loopback, &out.Loopback
		*out = new(NetworkDesignInterfacesLoopback)
		(*in).DeepCopyInto(*out)
	}
	if in.Underlay != nil {
		in, out := &in.Underlay, &out.Underlay
		*out = new(NetworkDesignInterfacesUnderlay)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignInterfaces.
func (in *NetworkDesignInterfaces) DeepCopy() *NetworkDesignInterfaces {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignInterfaces)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignInterfacesLoopback) DeepCopyInto(out *NetworkDesignInterfacesLoopback) {
	*out = *in
	in.NetworkDesignInterfaceParameters.DeepCopyInto(&out.NetworkDesignInterfaceParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignInterfacesLoopback.
func (in *NetworkDesignInterfacesLoopback) DeepCopy() *NetworkDesignInterfacesLoopback {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignInterfacesLoopback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignInterfacesUnderlay) DeepCopyInto(out *NetworkDesignInterfacesUnderlay) {
	*out = *in
	in.NetworkDesignInterfaceParameters.DeepCopyInto(&out.NetworkDesignInterfaceParameters)
	if in.BFD != nil {
		in, out := &in.BFD, &out.BFD
		*out = new(infrav1alpha1.BFDLinkParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignInterfacesUnderlay.
func (in *NetworkDesignInterfacesUnderlay) DeepCopy() *NetworkDesignInterfacesUnderlay {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignInterfacesUnderlay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignList) DeepCopyInto(out *NetworkDesignList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkDesign, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignList.
func (in *NetworkDesignList) DeepCopy() *NetworkDesignList {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkDesignList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocols) DeepCopyInto(out *NetworkDesignProtocols) {
	*out = *in
	if in.OSPF != nil {
		in, out := &in.OSPF, &out.OSPF
		*out = new(NetworkDesignProtocolsOSPF)
		(*in).DeepCopyInto(*out)
	}
	if in.ISIS != nil {
		in, out := &in.ISIS, &out.ISIS
		*out = new(NetworkDesignProtocolsISIS)
		(*in).DeepCopyInto(*out)
	}
	if in.IBGP != nil {
		in, out := &in.IBGP, &out.IBGP
		*out = new(NetworkDesignProtocolsIBGP)
		(*in).DeepCopyInto(*out)
	}
	if in.EBGP != nil {
		in, out := &in.EBGP, &out.EBGP
		*out = new(NetworkDesignProtocolsEBGP)
		(*in).DeepCopyInto(*out)
	}
	if in.BGPEVPN != nil {
		in, out := &in.BGPEVPN, &out.BGPEVPN
		*out = new(NetworkDesignProtocolsBGPEVPN)
		**out = **in
	}
	if in.BGPVPNv4 != nil {
		in, out := &in.BGPVPNv4, &out.BGPVPNv4
		*out = new(NetworkDesignProtocolsBGPVPNv4)
		**out = **in
	}
	if in.BGPVPNv6 != nil {
		in, out := &in.BGPVPNv6, &out.BGPVPNv6
		*out = new(NetworkDesignProtocolsBGPVPNv6)
		**out = **in
	}
	if in.BGPRouteTarget != nil {
		in, out := &in.BGPRouteTarget, &out.BGPRouteTarget
		*out = new(NetworkDesignProtocolsBGPRouteTarget)
		**out = **in
	}
	if in.BGPLabeledUnicastv4 != nil {
		in, out := &in.BGPLabeledUnicastv4, &out.BGPLabeledUnicastv4
		*out = new(NetworkDesignProtocolsBGPLabeledUnicastv4)
		**out = **in
	}
	if in.BGPLabeledUnicastv6 != nil {
		in, out := &in.BGPLabeledUnicastv6, &out.BGPLabeledUnicastv6
		*out = new(NetworkDesignProtocolsBGPLabeledUnicastv6)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocols.
func (in *NetworkDesignProtocols) DeepCopy() *NetworkDesignProtocols {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocols)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsBGPEVPN) DeepCopyInto(out *NetworkDesignProtocolsBGPEVPN) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsBGPEVPN.
func (in *NetworkDesignProtocolsBGPEVPN) DeepCopy() *NetworkDesignProtocolsBGPEVPN {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsBGPEVPN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsBGPLabeledUnicastv4) DeepCopyInto(out *NetworkDesignProtocolsBGPLabeledUnicastv4) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsBGPLabeledUnicastv4.
func (in *NetworkDesignProtocolsBGPLabeledUnicastv4) DeepCopy() *NetworkDesignProtocolsBGPLabeledUnicastv4 {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsBGPLabeledUnicastv4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsBGPLabeledUnicastv6) DeepCopyInto(out *NetworkDesignProtocolsBGPLabeledUnicastv6) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsBGPLabeledUnicastv6.
func (in *NetworkDesignProtocolsBGPLabeledUnicastv6) DeepCopy() *NetworkDesignProtocolsBGPLabeledUnicastv6 {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsBGPLabeledUnicastv6)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsBGPRouteTarget) DeepCopyInto(out *NetworkDesignProtocolsBGPRouteTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsBGPRouteTarget.
func (in *NetworkDesignProtocolsBGPRouteTarget) DeepCopy() *NetworkDesignProtocolsBGPRouteTarget {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsBGPRouteTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsBGPVPNv4) DeepCopyInto(out *NetworkDesignProtocolsBGPVPNv4) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsBGPVPNv4.
func (in *NetworkDesignProtocolsBGPVPNv4) DeepCopy() *NetworkDesignProtocolsBGPVPNv4 {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsBGPVPNv4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsBGPVPNv6) DeepCopyInto(out *NetworkDesignProtocolsBGPVPNv6) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsBGPVPNv6.
func (in *NetworkDesignProtocolsBGPVPNv6) DeepCopy() *NetworkDesignProtocolsBGPVPNv6 {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsBGPVPNv6)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsEBGP) DeepCopyInto(out *NetworkDesignProtocolsEBGP) {
	*out = *in
	if in.ASPool != nil {
		in, out := &in.ASPool, &out.ASPool
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsEBGP.
func (in *NetworkDesignProtocolsEBGP) DeepCopy() *NetworkDesignProtocolsEBGP {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsEBGP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsIBGP) DeepCopyInto(out *NetworkDesignProtocolsIBGP) {
	*out = *in
	if in.AS != nil {
		in, out := &in.AS, &out.AS
		*out = new(uint32)
		**out = **in
	}
	if in.RouteReflectors != nil {
		in, out := &in.RouteReflectors, &out.RouteReflectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsIBGP.
func (in *NetworkDesignProtocolsIBGP) DeepCopy() *NetworkDesignProtocolsIBGP {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsIBGP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsISIS) DeepCopyInto(out *NetworkDesignProtocolsISIS) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(string)
		**out = **in
	}
	if in.Areas != nil {
		in, out := &in.Areas, &out.Areas
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxECMPPaths != nil {
		in, out := &in.MaxECMPPaths, &out.MaxECMPPaths
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsISIS.
func (in *NetworkDesignProtocolsISIS) DeepCopy() *NetworkDesignProtocolsISIS {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsISIS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignProtocolsOSPF) DeepCopyInto(out *NetworkDesignProtocolsOSPF) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(string)
		**out = **in
	}
	if in.MaxECMPPaths != nil {
		in, out := &in.MaxECMPPaths, &out.MaxECMPPaths
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignProtocolsOSPF.
func (in *NetworkDesignProtocolsOSPF) DeepCopy() *NetworkDesignProtocolsOSPF {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignProtocolsOSPF)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignSpec) DeepCopyInto(out *NetworkDesignSpec) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = new(NetworkDesignInterfaces)
		(*in).DeepCopyInto(*out)
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = new(NetworkDesignProtocols)
		(*in).DeepCopyInto(*out)
	}
	if in.Encapsultation != nil {
		in, out := &in.Encapsultation, &out.Encapsultation
		*out = new(NetworkDesignEncapsulation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignSpec.
func (in *NetworkDesignSpec) DeepCopy() *NetworkDesignSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDesignStatus) DeepCopyInto(out *NetworkDesignStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDesignStatus.
func (in *NetworkDesignStatus) DeepCopy() *NetworkDesignStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkDesignStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDevice) DeepCopyInto(out *NetworkDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDevice.
func (in *NetworkDevice) DeepCopy() *NetworkDevice {
	if in == nil {
		return nil
	}
	out := new(NetworkDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceBFD) DeepCopyInto(out *NetworkDeviceBFD) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]*NetworkDeviceBFDInterface, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceBFDInterface)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceBFD.
func (in *NetworkDeviceBFD) DeepCopy() *NetworkDeviceBFD {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceBFD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceBFDInterface) DeepCopyInto(out *NetworkDeviceBFDInterface) {
	*out = *in
	out.SubInterfaceName = in.SubInterfaceName
	in.BFD.DeepCopyInto(&out.BFD)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceBFDInterface.
func (in *NetworkDeviceBFDInterface) DeepCopy() *NetworkDeviceBFDInterface {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceBFDInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceInterface) DeepCopyInto(out *NetworkDeviceInterface) {
	*out = *in
	if in.SubInterfaces != nil {
		in, out := &in.SubInterfaces, &out.SubInterfaces
		*out = make([]*NetworkDeviceInterfaceSubInterface, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceInterfaceSubInterface)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceInterface.
func (in *NetworkDeviceInterface) DeepCopy() *NetworkDeviceInterface {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceInterfaceSubInterface) DeepCopyInto(out *NetworkDeviceInterfaceSubInterface) {
	*out = *in
	if in.VLAN != nil {
		in, out := &in.VLAN, &out.VLAN
		*out = new(uint32)
		**out = **in
	}
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = new(NetworkDeviceInterfaceSubInterfaceIPv4)
		(*in).DeepCopyInto(*out)
	}
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(NetworkDeviceInterfaceSubInterfaceIPv6)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceInterfaceSubInterface.
func (in *NetworkDeviceInterfaceSubInterface) DeepCopy() *NetworkDeviceInterfaceSubInterface {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceInterfaceSubInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceInterfaceSubInterfaceIPv4) DeepCopyInto(out *NetworkDeviceInterfaceSubInterfaceIPv4) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceInterfaceSubInterfaceIPv4.
func (in *NetworkDeviceInterfaceSubInterfaceIPv4) DeepCopy() *NetworkDeviceInterfaceSubInterfaceIPv4 {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceInterfaceSubInterfaceIPv4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceInterfaceSubInterfaceIPv6) DeepCopyInto(out *NetworkDeviceInterfaceSubInterfaceIPv6) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceInterfaceSubInterfaceIPv6.
func (in *NetworkDeviceInterfaceSubInterfaceIPv6) DeepCopy() *NetworkDeviceInterfaceSubInterfaceIPv6 {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceInterfaceSubInterfaceIPv6)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceList) DeepCopyInto(out *NetworkDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceList.
func (in *NetworkDeviceList) DeepCopy() *NetworkDeviceList {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstance) DeepCopyInto(out *NetworkDeviceNetworkInstance) {
	*out = *in
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = new(NetworkDeviceNetworkInstanceProtocols)
		(*in).DeepCopyInto(*out)
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]*NetworkDeviceNetworkInstanceInterface, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceNetworkInstanceInterface)
				**out = **in
			}
		}
	}
	if in.VXLANInterface != nil {
		in, out := &in.VXLANInterface, &out.VXLANInterface
		*out = new(NetworkDeviceNetworkInstanceInterface)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstance.
func (in *NetworkDeviceNetworkInstance) DeepCopy() *NetworkDeviceNetworkInstance {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceInterface) DeepCopyInto(out *NetworkDeviceNetworkInstanceInterface) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceInterface.
func (in *NetworkDeviceNetworkInstanceInterface) DeepCopy() *NetworkDeviceNetworkInstanceInterface {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolBGP) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolBGP) {
	*out = *in
	if in.PeerGroups != nil {
		in, out := &in.PeerGroups, &out.PeerGroups
		*out = make([]*NetworkDeviceNetworkInstanceProtocolBGPPeerGroup, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceNetworkInstanceProtocolBGPPeerGroup)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Neighbors != nil {
		in, out := &in.Neighbors, &out.Neighbors
		*out = make([]*NetworkDeviceNetworkInstanceProtocolBGPNeighbor, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceNetworkInstanceProtocolBGPNeighbor)
				**out = **in
			}
		}
	}
	if in.DynamicNeighbors != nil {
		in, out := &in.DynamicNeighbors, &out.DynamicNeighbors
		*out = new(NetworkDeviceNetworkInstanceProtocolBGPDynamicNeighbors)
		(*in).DeepCopyInto(*out)
	}
	if in.AddressFamilies != nil {
		in, out := &in.AddressFamilies, &out.AddressFamilies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolBGP.
func (in *NetworkDeviceNetworkInstanceProtocolBGP) DeepCopy() *NetworkDeviceNetworkInstanceProtocolBGP {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolBGP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolBGPDynamicNeighbors) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolBGPDynamicNeighbors) {
	*out = *in
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]*NetworkDeviceNetworkInstanceProtocolBGPDynamicNeighborsInterface, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceNetworkInstanceProtocolBGPDynamicNeighborsInterface)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolBGPDynamicNeighbors.
func (in *NetworkDeviceNetworkInstanceProtocolBGPDynamicNeighbors) DeepCopy() *NetworkDeviceNetworkInstanceProtocolBGPDynamicNeighbors {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolBGPDynamicNeighbors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolBGPDynamicNeighborsInterface) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolBGPDynamicNeighborsInterface) {
	*out = *in
	out.SubInterfaceName = in.SubInterfaceName
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolBGPDynamicNeighborsInterface.
func (in *NetworkDeviceNetworkInstanceProtocolBGPDynamicNeighborsInterface) DeepCopy() *NetworkDeviceNetworkInstanceProtocolBGPDynamicNeighborsInterface {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolBGPDynamicNeighborsInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolBGPEVPN) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolBGPEVPN) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolBGPEVPN.
func (in *NetworkDeviceNetworkInstanceProtocolBGPEVPN) DeepCopy() *NetworkDeviceNetworkInstanceProtocolBGPEVPN {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolBGPEVPN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolBGPNeighbor) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolBGPNeighbor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolBGPNeighbor.
func (in *NetworkDeviceNetworkInstanceProtocolBGPNeighbor) DeepCopy() *NetworkDeviceNetworkInstanceProtocolBGPNeighbor {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolBGPNeighbor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolBGPPeerGroup) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolBGPPeerGroup) {
	*out = *in
	if in.AddressFamilies != nil {
		in, out := &in.AddressFamilies, &out.AddressFamilies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RouteReflector != nil {
		in, out := &in.RouteReflector, &out.RouteReflector
		*out = new(NetworkDeviceNetworkInstanceProtocolBGPPeerGroupRouteReflector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolBGPPeerGroup.
func (in *NetworkDeviceNetworkInstanceProtocolBGPPeerGroup) DeepCopy() *NetworkDeviceNetworkInstanceProtocolBGPPeerGroup {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolBGPPeerGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolBGPPeerGroupRouteReflector) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolBGPPeerGroupRouteReflector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolBGPPeerGroupRouteReflector.
func (in *NetworkDeviceNetworkInstanceProtocolBGPPeerGroupRouteReflector) DeepCopy() *NetworkDeviceNetworkInstanceProtocolBGPPeerGroupRouteReflector {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolBGPPeerGroupRouteReflector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolBGPVPN) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolBGPVPN) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolBGPVPN.
func (in *NetworkDeviceNetworkInstanceProtocolBGPVPN) DeepCopy() *NetworkDeviceNetworkInstanceProtocolBGPVPN {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolBGPVPN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolISIS) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolISIS) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]*NetworkDeviceNetworkInstanceProtocolISISInstance, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceNetworkInstanceProtocolISISInstance)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolISIS.
func (in *NetworkDeviceNetworkInstanceProtocolISIS) DeepCopy() *NetworkDeviceNetworkInstanceProtocolISIS {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolISIS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolISISInstance) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolISISInstance) {
	*out = *in
	if in.Net != nil {
		in, out := &in.Net, &out.Net
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]*NetworkDeviceNetworkInstanceProtocolISISInstanceInterface, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceNetworkInstanceProtocolISISInstanceInterface)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.MaxECMPPaths != nil {
		in, out := &in.MaxECMPPaths, &out.MaxECMPPaths
		*out = new(uint32)
		**out = **in
	}
	if in.AddressFamilies != nil {
		in, out := &in.AddressFamilies, &out.AddressFamilies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolISISInstance.
func (in *NetworkDeviceNetworkInstanceProtocolISISInstance) DeepCopy() *NetworkDeviceNetworkInstanceProtocolISISInstance {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolISISInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolISISInstanceInterface) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolISISInstanceInterface) {
	*out = *in
	out.SubInterfaceName = in.SubInterfaceName
	if in.NetworkType != nil {
		in, out := &in.NetworkType, &out.NetworkType
		*out = new(infrav1alpha1.NetworkType)
		**out = **in
	}
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = new(NetworkDeviceNetworkInstanceProtocolISISInstanceInterfaceIPv4)
		**out = **in
	}
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(NetworkDeviceNetworkInstanceProtocolISISInstanceInterfaceIPv6)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolISISInstanceInterface.
func (in *NetworkDeviceNetworkInstanceProtocolISISInstanceInterface) DeepCopy() *NetworkDeviceNetworkInstanceProtocolISISInstanceInterface {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolISISInstanceInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolISISInstanceInterfaceIPv4) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolISISInstanceInterfaceIPv4) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolISISInstanceInterfaceIPv4.
func (in *NetworkDeviceNetworkInstanceProtocolISISInstanceInterfaceIPv4) DeepCopy() *NetworkDeviceNetworkInstanceProtocolISISInstanceInterfaceIPv4 {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolISISInstanceInterfaceIPv4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolISISInstanceInterfaceIPv6) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolISISInstanceInterfaceIPv6) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolISISInstanceInterfaceIPv6.
func (in *NetworkDeviceNetworkInstanceProtocolISISInstanceInterfaceIPv6) DeepCopy() *NetworkDeviceNetworkInstanceProtocolISISInstanceInterfaceIPv6 {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolISISInstanceInterfaceIPv6)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolOSPF) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolOSPF) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]*NetworkDeviceNetworkInstanceProtocolOSPFInstance, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceNetworkInstanceProtocolOSPFInstance)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolOSPF.
func (in *NetworkDeviceNetworkInstanceProtocolOSPF) DeepCopy() *NetworkDeviceNetworkInstanceProtocolOSPF {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolOSPF)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolOSPFInstance) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolOSPFInstance) {
	*out = *in
	if in.Areas != nil {
		in, out := &in.Areas, &out.Areas
		*out = make([]*NetworkDeviceNetworkInstanceProtocolOSPFInstanceArea, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceNetworkInstanceProtocolOSPFInstanceArea)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.MaxECMPPaths != nil {
		in, out := &in.MaxECMPPaths, &out.MaxECMPPaths
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolOSPFInstance.
func (in *NetworkDeviceNetworkInstanceProtocolOSPFInstance) DeepCopy() *NetworkDeviceNetworkInstanceProtocolOSPFInstance {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolOSPFInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolOSPFInstanceArea) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolOSPFInstanceArea) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]*NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaInterface, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaInterface)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.NSSA != nil {
		in, out := &in.NSSA, &out.NSSA
		*out = new(NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaNSSA)
		**out = **in
	}
	if in.Stub != nil {
		in, out := &in.Stub, &out.Stub
		*out = new(NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaStub)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolOSPFInstanceArea.
func (in *NetworkDeviceNetworkInstanceProtocolOSPFInstanceArea) DeepCopy() *NetworkDeviceNetworkInstanceProtocolOSPFInstanceArea {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolOSPFInstanceArea)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaInterface) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaInterface) {
	*out = *in
	out.SubInterfaceName = in.SubInterfaceName
	if in.NetworkType != nil {
		in, out := &in.NetworkType, &out.NetworkType
		*out = new(infrav1alpha1.NetworkType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaInterface.
func (in *NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaInterface) DeepCopy() *NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaInterface {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaNSSA) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaNSSA) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaNSSA.
func (in *NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaNSSA) DeepCopy() *NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaNSSA {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaNSSA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaStub) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaStub) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaStub.
func (in *NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaStub) DeepCopy() *NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaStub {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocolOSPFInstanceAreaStub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceNetworkInstanceProtocols) DeepCopyInto(out *NetworkDeviceNetworkInstanceProtocols) {
	*out = *in
	if in.BGP != nil {
		in, out := &in.BGP, &out.BGP
		*out = new(NetworkDeviceNetworkInstanceProtocolBGP)
		(*in).DeepCopyInto(*out)
	}
	if in.BGPEVPN != nil {
		in, out := &in.BGPEVPN, &out.BGPEVPN
		*out = new(NetworkDeviceNetworkInstanceProtocolBGPEVPN)
		**out = **in
	}
	if in.BGPVPN != nil {
		in, out := &in.BGPVPN, &out.BGPVPN
		*out = new(NetworkDeviceNetworkInstanceProtocolBGPVPN)
		**out = **in
	}
	if in.ISIS != nil {
		in, out := &in.ISIS, &out.ISIS
		*out = new(NetworkDeviceNetworkInstanceProtocolISIS)
		(*in).DeepCopyInto(*out)
	}
	if in.OSPF != nil {
		in, out := &in.OSPF, &out.OSPF
		*out = new(NetworkDeviceNetworkInstanceProtocolOSPF)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceNetworkInstanceProtocols.
func (in *NetworkDeviceNetworkInstanceProtocols) DeepCopy() *NetworkDeviceNetworkInstanceProtocols {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceNetworkInstanceProtocols)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceRoutingPolicy) DeepCopyInto(out *NetworkDeviceRoutingPolicy) {
	*out = *in
	if in.IPv4Prefixes != nil {
		in, out := &in.IPv4Prefixes, &out.IPv4Prefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IPv6Prefixes != nil {
		in, out := &in.IPv6Prefixes, &out.IPv6Prefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceRoutingPolicy.
func (in *NetworkDeviceRoutingPolicy) DeepCopy() *NetworkDeviceRoutingPolicy {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceRoutingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceSpec) DeepCopyInto(out *NetworkDeviceSpec) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]*NetworkDeviceInterface, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceInterface)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.NetworkInstances != nil {
		in, out := &in.NetworkInstances, &out.NetworkInstances
		*out = make([]*NetworkDeviceNetworkInstance, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceNetworkInstance)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TunnelInterfaces != nil {
		in, out := &in.TunnelInterfaces, &out.TunnelInterfaces
		*out = make([]*NetworkDeviceTunnelInterface, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceTunnelInterface)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.RoutingPolicies != nil {
		in, out := &in.RoutingPolicies, &out.RoutingPolicies
		*out = make([]*NetworkDeviceRoutingPolicy, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceRoutingPolicy)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.System != nil {
		in, out := &in.System, &out.System
		*out = new(NetworkDeviceSystem)
		(*in).DeepCopyInto(*out)
	}
	if in.BFD != nil {
		in, out := &in.BFD, &out.BFD
		*out = new(NetworkDeviceBFD)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceSpec.
func (in *NetworkDeviceSpec) DeepCopy() *NetworkDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceStatus) DeepCopyInto(out *NetworkDeviceStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceStatus.
func (in *NetworkDeviceStatus) DeepCopy() *NetworkDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceSystem) DeepCopyInto(out *NetworkDeviceSystem) {
	*out = *in
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = new(NetworkDeviceSystemProtocols)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceSystem.
func (in *NetworkDeviceSystem) DeepCopy() *NetworkDeviceSystem {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceSystemProtocols) DeepCopyInto(out *NetworkDeviceSystemProtocols) {
	*out = *in
	if in.BGPVPN != nil {
		in, out := &in.BGPVPN, &out.BGPVPN
		*out = new(NetworkDeviceSystemProtocolsBGPVPN)
		**out = **in
	}
	if in.BGPEVPN != nil {
		in, out := &in.BGPEVPN, &out.BGPEVPN
		*out = new(NetworkDeviceSystemProtocolsBGPEVPN)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceSystemProtocols.
func (in *NetworkDeviceSystemProtocols) DeepCopy() *NetworkDeviceSystemProtocols {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceSystemProtocols)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceSystemProtocolsBGPEVPN) DeepCopyInto(out *NetworkDeviceSystemProtocolsBGPEVPN) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceSystemProtocolsBGPEVPN.
func (in *NetworkDeviceSystemProtocolsBGPEVPN) DeepCopy() *NetworkDeviceSystemProtocolsBGPEVPN {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceSystemProtocolsBGPEVPN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceSystemProtocolsBGPVPN) DeepCopyInto(out *NetworkDeviceSystemProtocolsBGPVPN) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceSystemProtocolsBGPVPN.
func (in *NetworkDeviceSystemProtocolsBGPVPN) DeepCopy() *NetworkDeviceSystemProtocolsBGPVPN {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceSystemProtocolsBGPVPN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceTunnelInterface) DeepCopyInto(out *NetworkDeviceTunnelInterface) {
	*out = *in
	if in.SubInterfaces != nil {
		in, out := &in.SubInterfaces, &out.SubInterfaces
		*out = make([]*NetworkDeviceTunnelInterfaceSubInterface, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkDeviceTunnelInterfaceSubInterface)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceTunnelInterface.
func (in *NetworkDeviceTunnelInterface) DeepCopy() *NetworkDeviceTunnelInterface {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceTunnelInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDeviceTunnelInterfaceSubInterface) DeepCopyInto(out *NetworkDeviceTunnelInterfaceSubInterface) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDeviceTunnelInterfaceSubInterface.
func (in *NetworkDeviceTunnelInterfaceSubInterface) DeepCopy() *NetworkDeviceTunnelInterfaceSubInterface {
	if in == nil {
		return nil
	}
	out := new(NetworkDeviceTunnelInterfaceSubInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInterface) DeepCopyInto(out *NetworkInterface) {
	*out = *in
	if in.Bridge != nil {
		in, out := &in.Bridge, &out.Bridge
		*out = new(string)
		**out = **in
	}
	if in.EndPoint != nil {
		in, out := &in.EndPoint, &out.EndPoint
		*out = new(string)
		**out = **in
	}
	if in.NodeID != nil {
		in, out := &in.NodeID, &out.NodeID
		*out = new(infrav1alpha1.NodeID)
		**out = **in
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]*NetworkInterfaceAddress, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkInterfaceAddress)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.VLANID != nil {
		in, out := &in.VLANID, &out.VLANID
		*out = new(uint32)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = new(NetworkInterfaceProtocols)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInterface.
func (in *NetworkInterface) DeepCopy() *NetworkInterface {
	if in == nil {
		return nil
	}
	out := new(NetworkInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInterfaceAddress) DeepCopyInto(out *NetworkInterfaceAddress) {
	*out = *in
	if in.Attribute != nil {
		in, out := &in.Attribute, &out.Attribute
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInterfaceAddress.
func (in *NetworkInterfaceAddress) DeepCopy() *NetworkInterfaceAddress {
	if in == nil {
		return nil
	}
	out := new(NetworkInterfaceAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInterfaceProtocols) DeepCopyInto(out *NetworkInterfaceProtocols) {
	*out = *in
	if in.BGP != nil {
		in, out := &in.BGP, &out.BGP
		*out = new(NetworkConfigProtocolsBGP)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInterfaceProtocols.
func (in *NetworkInterfaceProtocols) DeepCopy() *NetworkInterfaceProtocols {
	if in == nil {
		return nil
	}
	out := new(NetworkInterfaceProtocols)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkList) DeepCopyInto(out *NetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Network, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkList.
func (in *NetworkList) DeepCopy() *NetworkList {
	if in == nil {
		return nil
	}
	out := new(NetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRouter) DeepCopyInto(out *NetworkRouter) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]*NetworkInterface, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkInterface)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRouter.
func (in *NetworkRouter) DeepCopy() *NetworkRouter {
	if in == nil {
		return nil
	}
	out := new(NetworkRouter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	if in.Bridges != nil {
		in, out := &in.Bridges, &out.Bridges
		*out = make([]*NetworkBridge, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkBridge)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Routers != nil {
		in, out := &in.Routers, &out.Routers
		*out = make([]*NetworkRouter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkRouter)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkStatus) DeepCopyInto(out *NetworkStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.DevicesConfigStatus != nil {
		in, out := &in.DevicesConfigStatus, &out.DevicesConfigStatus
		*out = make([]*NetworkStatusDeviceStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkStatusDeviceStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.DevicesDeployStatus != nil {
		in, out := &in.DevicesDeployStatus, &out.DevicesDeployStatus
		*out = make([]*NetworkStatusDeviceStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkStatusDeviceStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkStatus.
func (in *NetworkStatus) DeepCopy() *NetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkStatusDeviceStatus) DeepCopyInto(out *NetworkStatusDeviceStatus) {
	*out = *in
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkStatusDeviceStatus.
func (in *NetworkStatusDeviceStatus) DeepCopy() *NetworkStatusDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkStatusDeviceStatus)
	in.DeepCopyInto(out)
	return out
}
