apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kuidapps
  name: kuidapps-clusterrole
rules:
- apiGroups: [""]
  resources: [events, configmaps]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [topo.app.kuid.dev]
  resources: [topologies, topologies/status]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [infra.be.kuid.dev]
  resources: [nodes, nodes/status]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [infra.be.kuid.dev]
  resources: [links, links/status]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [infra.be.kuid.dev]
  resources: [endpoints, endpoints/status]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [ipam.be.kuid.dev]
  resources: [ipindices, ipindices/status]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [ipam.be.kuid.dev]
  resources: [ipclaims, ipclaims/status]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [as.be.kuid.dev]
  resources: [asindices, asindices/status]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [as.be.kuid.dev]
  resources: [asclaims, asclaims/status]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [genid.be.kuid.dev]
  resources: [genidindices, genidindices/status]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [genid.be.kuid.dev]
  resources: [genidclaims, genidclaims/status]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [network.app.kuid.dev]
  resources: [networkconfigs, networkconfigs/status]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [network.app.kuid.dev]
  resources: [networks, networks/status]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [network.app.kuid.dev]
  resources: [networkdevices, networkdevices/status]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [config.sdcio.dev]
  resources: [configs, configs/status]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: ["pkg.pkgserver.dev"]
  resources: ["packagerevisions", "packagerevisions/status"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: ["pkg.pkgserver.dev"]
  resources: ["packagerevisionresourceses", "packagerevisionresourceses/status"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]